{% set version = "0.1.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-qrcode
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qrcode_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qrcode/qrcode_{{ version }}.tar.gz
  sha256: d89ced2609ca39020c53c8a82d197843bc602843be7c585f0bd377e52b3d56aa

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.utils
    - r-assertthat
    - r-stringr
  run:
    - r-base
    - r-r.utils
    - r-assertthat
    - r-stringr

test:
  commands:
    - $R -e "library('qrcode')"           # [not win]
    - "\"%R%\" -e \"library('qrcode')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=qrcode
  license: GPL-3.0-only
  summary: Create QRcode in R.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
