{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-qrcode
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qrcode_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qrcode/qrcode_{{ version }}.tar.gz
  sha256: 76bb51e3eba538e9f93d5a0a601b0ebdf2b0bf6b2c9ef3f0b3621460d4dbb31d

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-assertthat
    - r-knitr
  run:
    - r-base
    - r-assertthat
    - r-knitr

test:
  commands:
    - $R -e "library('qrcode')"           # [not win]
    - "\"%R%\" -e \"library('qrcode')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=qrcode
  license: GPL-3.0-only
  summary: Create QRcode in R.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
