appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Fbw9LcHPsI3v3yj28ooqQFjhk5pdto8kmpOAbhS+JJo6EG2cxQq/SUbmPIwGqziJiOv6kRjrox4msGk6B3gYhjztIQuZ2XGbzKi6BJ/uXCMVzp46JkUp0kk0wEb+LaYNGQDB1xvsk4r4dI7wYF4FSXZxclMXLmuEA+QrlAaB9UbKE4TmbbHek+iAZfBdaSJnJ63ZA5/5k3QBS+giTBiMCFGjdxPmIDbyfxF2G9lctfxRtT2QF8Yx6zOvRo2Brc/ptlp8Ep2/p0TI0VejEScupocWiDl7e183u0lnksKcg2uOfU2OzsHkle4plmgs2JwffKF7cZKDUPM8Ian+5xn6y1g+WvJ6kIFUvnqk1EabRZzpQiYHYKyOmajvpNeEDmMEtfE1IcXqOpCySkJRHwiVcF8WiDwRs/Ocv0YtFaoEfnbdRpvr0EGJ11QWgZpSQSuZmdjo+cIiI0NDF62+s8P8Onp5NUAYcV/HIdrckgAG+aBT/93tkFUH7dlqrUXEAzverRgmvJ7oBbFmcye0ODWi1dcIS3jbfdslfac5QjJiA6a+T14axFwIyD4bTsAdBwXmI13EQypX3a4wCikAqQX7jsS+JqTanT+MhHnO4P1AyKmfft2xn75wjsApxzRDuF08ut8vaKJSstc5yaZ1eCwKjTAk4bMt9RjVHc004UztQBw=
